apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-devops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MouradOuammou/nodejs-devops-app.git
    targetRevision: HEAD
    path: helm/nodejs-devops-app
    helm:
      values:
        image:
          repository: MouradOuammou/nodejs-devops-app
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true